'use client'

import { useState } from 'react'
import { Scenario, HPI, MedicalBackground, ProblemRepresentation as ProblemRep } from '@/data/scenarios'

type Props = {
  scenario: Scenario
  hpi: HPI
  background: MedicalBackground
  onComplete: (problemRep: ProblemRep) => void
}

export default function ProblemRepresentation({ scenario, hpi, background, onComplete }: Props) {
  const [summary, setSummary] = useState('')
  const [autoGenerated, setAutoGenerated] = useState(false)

  const generateAutoSummary = () => {
    const { patientPersona } = scenario
    const age = patientPersona.age
    const gender = patientPersona.gender
    const riskFactors: string[] = []
    
    if (background.pastMedicalHistory && background.pastMedicalHistory.length > 0) {
      riskFactors.push(background.pastMedicalHistory.join(', '))
    }
    if (background.socialHistory?.smoking) {
      riskFactors.push('smoking history')
    }

    const timeCourse = hpi.timing || hpi.onset || 'recent'
    const keySymptoms = [
      hpi.quality,
      hpi.radiation && `radiating to ${hpi.radiation}`,
      hpi.severity && `severity ${hpi.severity}/10`
    ].filter(Boolean).join(', ')

    const associated = hpi.associatedSymptoms?.join(', ') || ''

    const generated = `${age}-year-old ${gender.toLowerCase()}${riskFactors.length > 0 ? ` with ${riskFactors.join(', ')}` : ''} presenting with ${timeCourse} ${scenario.patientPersona.chiefComplaint.toLowerCase()}${keySymptoms ? ` (${keySymptoms})` : ''}${associated ? ` with associated ${associated}` : ''}.`

    setSummary(generated)
    setAutoGenerated(true)
  }

  const handleSubmit = () => {
    if (summary.trim()) {
      onComplete({ summary })
    }
  }

  return (
    <div className="bg-white rounded-lg shadow-md p-6 mb-6">
      <h2 className="text-2xl font-bold text-gray-900 mb-4">Step 4: Problem Representation</h2>
      <p className="text-gray-600 mb-6">
        Compress the whole story into a clear one-sentence clinical snapshot.
      </p>

      <div className="mb-4">
        <button
          onClick={generateAutoSummary}
          className="px-4 py-2 bg-blue-100 text-blue-700 rounded-md hover:bg-blue-200 text-sm font-medium"
        >
          Auto-Generate from History
        </button>
        {autoGenerated && (
          <p className="mt-2 text-sm text-gray-600">You can edit the generated summary below.</p>
        )}
      </div>

      <div className="mb-4">
        <label className="block text-sm font-medium text-gray-700 mb-2">
          One-Sentence Summary
        </label>
        <textarea
          value={summary}
          onChange={(e) => setSummary(e.target.value)}
          placeholder="e.g., 54-year-old male with hypertension and high cholesterol presenting with acute exertional chest pain (pressure quality, 8/10 severity, radiating to left arm) with associated shortness of breath and diaphoresis."
          rows={4}
          className="w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-primary-500"
        />
        <p className="mt-2 text-xs text-gray-500">
          Template: [Age][sex] with [risk factors] presenting with [time course] [key symptom descriptors] with [key associated symptoms].
        </p>
      </div>

      <button
        onClick={handleSubmit}
        disabled={!summary.trim()}
        className="w-full px-6 py-3 bg-primary-600 text-white rounded-md hover:bg-primary-700 disabled:opacity-50 disabled:cursor-not-allowed transition font-medium"
      >
        Continue to Physical Exam
      </button>
    </div>
  )
}

